name: Daily Rate Tracker

on:
  push:
  schedule:
    - cron: '0 14-22 * * 1-5' # Runs at 9:00 AM EST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track-rates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests yfinance

      - name: Run Script
        run: python main.py

      - name: Save Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily Rate Update"
          file_pattern: interest_rate_log.csv
